# netlify.toml
[build]
  command = "vite build"
  publish = "dist"

[dev]
  command = "vite"        # cómo arrancas el front en dev
  port = 8888             # puerto expuesto por Netlify Dev
  targetPort = 5173       # puerto donde Vite sirve la app
  framework = "vite"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
