[build]
  command = ""
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
framework = "#custom"
# no lanzamos Vite desde Netlify; ya lo arranca solo
targetPort = 5173
port = 9999
autoLaunch = false
