# netlify.toml
[build]
  command = "vite build"
  publish = "dist"

[dev]
  command = "vite"                # cómo arrancas el front en desarrollo
  port = 5173                     # puerto Vite (Netlify lo proxifica en 8888)
  targetPort = 5173
  framework = "vite"

[functions]
  directory = "netlify/functions" # donde viven tus serverless functions
  node_bundler = "esbuild"
