[build]
  command = "cd web && npm ci && npm run build"
  publish = "web/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["db/**", "shared/**"] # si tu API lee cosas de estas carpetas

# (solo para desarrollo local con netlify dev + Vite corriendo en 5174)
[dev]
framework = "#custom"
command = "npm run dev --prefix web"
targetPort = 5174
port = 8889
autoLaunch = false
