[build]
  command = ""         # no construyas frontend
  publish = "."        # cualquier carpeta (no se usa)

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Solo para desarrollo local
[dev]
framework = "#custom"
command = "npm run dev"
targetPort = 5174
port = 8889
autoLaunch = false
