[build]
  command = "npm ci && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["db/**", "shared/**"]

# Solo para desarrollo local con `netlify dev`
[dev]
framework = "#custom"
command = "npm run dev"
targetPort = 5174   # puerto de Vite en local
port = 8889         # puerto de Netlify Dev
autoLaunch = false
