[build]
  command = "npm ci && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["db/**", "shared/**"]  # si existen; si no, puedes quitar esta línea

# Solo para desarrollo local
[dev]
framework = "#custom"
command = "npm run dev"
targetPort = 5174
port = 8889
autoLaunch = false
